name: Linters

on: pull_request

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --color